name: Upload metadata

on:
  workflow_dispatch:
    inputs:
      repository:
        required: true
      token:
        required: true
      whats_new:
      app_rating_config:
        type: boolean

jobs:
  upload_metadata:
    runs-on: macos-15
    steps:
      - name: Mask Input Parameters
        run: |
          REPOSITORY=$(jq -r '.inputs.repository' "$GITHUB_EVENT_PATH")
          TOKEN=$(jq -r '.inputs.token' "$GITHUB_EVENT_PATH")
          echo "::add-mask::$REPOSITORY"
          echo "::add-mask::$TOKEN"

      - name: Notify webhook
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
        run: |
          curl -X POST -F "token=${{ github.event.inputs.token }}" -F "workflow_run_id=${{ github.run_id }}" "$BASE_URL/webhook.php"

      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repository }}
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 1

      - name: Download metadata CSV file
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
        run: |
          curl -o fastlane/metadata.csv "$BASE_URL/metadata/${{ github.event.inputs.token }}.csv"

      - name: Upload metadata
        run: |
          # TODO: return to - bundle exec fastlane upload_metadata
        env:
          WHATS_NEW: ${{ github.event.inputs.whats_new }}
          APP_RATING_CONFIG: ${{ github.event.inputs.app_rating_config }}

      - name: Commit metadata
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          file_pattern: 'fastlane/metadata/* fastlane/metadata.csv'
          commit_message: 'Update metadata'